--------------------------------------------------------
--  Fichier créé - mercredi-mai-05-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence COMMANDES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FARAH"."COMMANDES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPLOYE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FARAH"."EMPLOYE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EQUIPEMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FARAH"."EQUIPEMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EQUIPEMENT_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FARAH"."EQUIPEMENT_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MENU_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FARAH"."MENU_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PLATS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FARAH"."PLATS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PLATS_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "FARAH"."PLATS_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRODUITS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FARAH"."PRODUITS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SUPPLEMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FARAH"."SUPPLEMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FARAH"."USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence VEHICULE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FARAH"."VEHICULE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CARTE_FIDELITE
--------------------------------------------------------

  CREATE TABLE "FARAH"."CARTE_FIDELITE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NUMERO" VARCHAR2(20 BYTE), 
	"DATE_CREATION" VARCHAR2(20 BYTE), 
	"NB_POINTS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "FARAH"."CLIENT" 
   (	"ID" VARCHAR2(20 BYTE), 
	"AGE" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDEPLAT
--------------------------------------------------------

  CREATE TABLE "FARAH"."COMMANDEPLAT" 
   (	"NUMC" NUMBER, 
	"ID_PLAT" NUMBER, 
	"QTY" NUMBER DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDES
--------------------------------------------------------

  CREATE TABLE "FARAH"."COMMANDES" 
   (	"NUMC" NUMBER, 
	"IDEMPLOYE" NUMBER, 
	"DATEC" DATE DEFAULT sysdate, 
	"PRIXTOT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "FARAH"."EMPLOYE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"TELEPHONE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENT
--------------------------------------------------------

  CREATE TABLE "FARAH"."EQUIPEMENT" 
   (	"ID_EQUIPEMENT" NUMBER, 
	"MATERIEL" VARCHAR2(20 BYTE), 
	"POSTE" VARCHAR2(20 BYTE), 
	"ID_EMPLOYEE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "FARAH"."FOURNISSEUR" 
   (	"ID_FOURNISSEUR" NUMBER, 
	"NOM_FOURNISSEUR" VARCHAR2(20 BYTE), 
	"PRENOM_FOURNISSEUR" VARCHAR2(20 BYTE), 
	"TEL" NUMBER, 
	"ID_PRODUIT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LIVRAISONS
--------------------------------------------------------

  CREATE TABLE "FARAH"."LIVRAISONS" 
   (	"ID" NUMBER, 
	"ID_V" NUMBER, 
	"ID_LIVREUR" NUMBER, 
	"DATEC" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOGIN
--------------------------------------------------------

  CREATE TABLE "FARAH"."LOGIN" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWOED" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "FARAH"."MENU" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRIX" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PANIER
--------------------------------------------------------

  CREATE TABLE "FARAH"."PANIER" 
   (	"ID" NUMBER, 
	"NOM_PRODUIT" VARCHAR2(20 BYTE), 
	"CATEGORIE" VARCHAR2(20 BYTE), 
	"PRIX" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PLATS
--------------------------------------------------------

  CREATE TABLE "FARAH"."PLATS" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"CATEGORIE" VARCHAR2(20 BYTE), 
	"PRIX" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"ID_MENU" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUITS
--------------------------------------------------------

  CREATE TABLE "FARAH"."PRODUITS" 
   (	"ID" NUMBER, 
	"NOM_PRODUIT" VARCHAR2(20 BYTE), 
	"CATEGORIE" VARCHAR2(20 BYTE), 
	"PRIX" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SUPPCOM
--------------------------------------------------------

  CREATE TABLE "FARAH"."SUPPCOM" 
   (	"NUMC" NUMBER, 
	"IDS" NUMBER, 
	"QTY" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SUPPLEMENT
--------------------------------------------------------

  CREATE TABLE "FARAH"."SUPPLEMENT" 
   (	"IDS" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "FARAH"."USERS" 
   (	"ID" NUMBER, 
	"LOGIN" VARCHAR2(20 BYTE), 
	"PASWORD" VARCHAR2(20 BYTE), 
	"ID_EMP" NUMBER, 
	"EMAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VEHICULE
--------------------------------------------------------

  CREATE TABLE "FARAH"."VEHICULE" 
   (	"ID" NUMBER, 
	"ETAT" VARCHAR2(20 BYTE), 
	"MODELE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into FARAH.CARTE_FIDELITE
SET DEFINE OFF;
REM INSERTING into FARAH.CLIENT
SET DEFINE OFF;
Insert into FARAH.CLIENT (ID,AGE,NOM,ADRESSE,PRENOM) values ('12','4','far','12','hasna');
REM INSERTING into FARAH.COMMANDEPLAT
SET DEFINE OFF;
REM INSERTING into FARAH.COMMANDES
SET DEFINE OFF;
Insert into FARAH.COMMANDES (NUMC,IDEMPLOYE,DATEC,PRIXTOT) values ('5','0',to_date('30/04/21','DD/MM/RR'),'0');
Insert into FARAH.COMMANDES (NUMC,IDEMPLOYE,DATEC,PRIXTOT) values ('2','0',to_date('30/04/21','DD/MM/RR'),'0');
Insert into FARAH.COMMANDES (NUMC,IDEMPLOYE,DATEC,PRIXTOT) values ('3','0',to_date('30/04/21','DD/MM/RR'),'0');
Insert into FARAH.COMMANDES (NUMC,IDEMPLOYE,DATEC,PRIXTOT) values ('4','0',to_date('30/04/21','DD/MM/RR'),'0');
Insert into FARAH.COMMANDES (NUMC,IDEMPLOYE,DATEC,PRIXTOT) values ('6','0',to_date('30/04/21','DD/MM/RR'),'0');
Insert into FARAH.COMMANDES (NUMC,IDEMPLOYE,DATEC,PRIXTOT) values ('7','0',to_date('30/04/21','DD/MM/RR'),'0');
REM INSERTING into FARAH.EMPLOYE
SET DEFINE OFF;
Insert into FARAH.EMPLOYE (ID,NOM,PRENOM,ADRESSE,TELEPHONE) values ('5','chef de cuisine',null,null,'0');
Insert into FARAH.EMPLOYE (ID,NOM,PRENOM,ADRESSE,TELEPHONE) values ('12','caissier',null,null,'0');
Insert into FARAH.EMPLOYE (ID,NOM,PRENOM,ADRESSE,TELEPHONE) values ('54','employe',null,'11','0');
Insert into FARAH.EMPLOYE (ID,NOM,PRENOM,ADRESSE,TELEPHONE) values ('0','caissier',null,'9','0');
Insert into FARAH.EMPLOYE (ID,NOM,PRENOM,ADRESSE,TELEPHONE) values ('7','caissier',null,'5','0');
Insert into FARAH.EMPLOYE (ID,NOM,PRENOM,ADRESSE,TELEPHONE) values ('77','employe',null,'12','0');
Insert into FARAH.EMPLOYE (ID,NOM,PRENOM,ADRESSE,TELEPHONE) values ('85','employe',null,'13','0');
REM INSERTING into FARAH.EQUIPEMENT
SET DEFINE OFF;
Insert into FARAH.EQUIPEMENT (ID_EQUIPEMENT,MATERIEL,POSTE,ID_EMPLOYEE) values ('1','chaise',null,'0');
Insert into FARAH.EQUIPEMENT (ID_EQUIPEMENT,MATERIEL,POSTE,ID_EMPLOYEE) values ('12','llll',null,'5');
Insert into FARAH.EQUIPEMENT (ID_EQUIPEMENT,MATERIEL,POSTE,ID_EMPLOYEE) values ('16','friteuse',null,'0');
Insert into FARAH.EQUIPEMENT (ID_EQUIPEMENT,MATERIEL,POSTE,ID_EMPLOYEE) values ('6','friteuse',null,'0');
Insert into FARAH.EQUIPEMENT (ID_EQUIPEMENT,MATERIEL,POSTE,ID_EMPLOYEE) values ('5','table',null,'0');
Insert into FARAH.EQUIPEMENT (ID_EQUIPEMENT,MATERIEL,POSTE,ID_EMPLOYEE) values ('2','four','chef de cuisine','0');
Insert into FARAH.EQUIPEMENT (ID_EQUIPEMENT,MATERIEL,POSTE,ID_EMPLOYEE) values ('3','four','employe','0');
Insert into FARAH.EQUIPEMENT (ID_EQUIPEMENT,MATERIEL,POSTE,ID_EMPLOYEE) values ('4','four','chef de cuisine','0');
Insert into FARAH.EQUIPEMENT (ID_EQUIPEMENT,MATERIEL,POSTE,ID_EMPLOYEE) values ('9','four','caissier','0');
REM INSERTING into FARAH.FOURNISSEUR
SET DEFINE OFF;
Insert into FARAH.FOURNISSEUR (ID_FOURNISSEUR,NOM_FOURNISSEUR,PRENOM_FOURNISSEUR,TEL,ID_PRODUIT) values ('1','ll','lll','12','12');
REM INSERTING into FARAH.LIVRAISONS
SET DEFINE OFF;
Insert into FARAH.LIVRAISONS (ID,ID_V,ID_LIVREUR,DATEC) values ('0','12','0',null);
Insert into FARAH.LIVRAISONS (ID,ID_V,ID_LIVREUR,DATEC) values ('7','12','0',null);
REM INSERTING into FARAH.LOGIN
SET DEFINE OFF;
REM INSERTING into FARAH.MENU
SET DEFINE OFF;
Insert into FARAH.MENU (ID,NOM,PRIX,DESCRIPTION) values ('42','entrees','fritte,scaloppe','16');
Insert into FARAH.MENU (ID,NOM,PRIX,DESCRIPTION) values ('43',null,null,null);
Insert into FARAH.MENU (ID,NOM,PRIX,DESCRIPTION) values ('61','salades',null,null);
Insert into FARAH.MENU (ID,NOM,PRIX,DESCRIPTION) values ('81','entrees',null,null);
Insert into FARAH.MENU (ID,NOM,PRIX,DESCRIPTION) values ('82','plat',null,null);
Insert into FARAH.MENU (ID,NOM,PRIX,DESCRIPTION) values ('83','boisons',null,null);
Insert into FARAH.MENU (ID,NOM,PRIX,DESCRIPTION) values ('84','deserts','ll','mmm');
Insert into FARAH.MENU (ID,NOM,PRIX,DESCRIPTION) values ('85','salades','lll','17');
Insert into FARAH.MENU (ID,NOM,PRIX,DESCRIPTION) values ('86',null,null,null);
Insert into FARAH.MENU (ID,NOM,PRIX,DESCRIPTION) values ('87','llll','22','15');
Insert into FARAH.MENU (ID,NOM,PRIX,DESCRIPTION) values ('88','deserts','lllllll','14');
REM INSERTING into FARAH.PANIER
SET DEFINE OFF;
REM INSERTING into FARAH.PLATS
SET DEFINE OFF;
Insert into FARAH.PLATS (ID,NOM,CATEGORIE,PRIX,TYPE,ID_MENU) values ('61','Mmm','Mm','1','special','61');
Insert into FARAH.PLATS (ID,NOM,CATEGORIE,PRIX,TYPE,ID_MENU) values ('41','Mmm','Ll','2','special','42');
Insert into FARAH.PLATS (ID,NOM,CATEGORIE,PRIX,TYPE,ID_MENU) values ('42','Pizza','1','15','special','42');
Insert into FARAH.PLATS (ID,NOM,CATEGORIE,PRIX,TYPE,ID_MENU) values ('62','Mmm','Mm','12','special','42');
Insert into FARAH.PLATS (ID,NOM,CATEGORIE,PRIX,TYPE,ID_MENU) values ('63','Mmm','Mm','12','special','42');
REM INSERTING into FARAH.PRODUITS
SET DEFINE OFF;
Insert into FARAH.PRODUITS (ID,NOM_PRODUIT,CATEGORIE,PRIX) values ('12','mmm',null,'0');
Insert into FARAH.PRODUITS (ID,NOM_PRODUIT,CATEGORIE,PRIX) values ('5',null,null,'15');
Insert into FARAH.PRODUITS (ID,NOM_PRODUIT,CATEGORIE,PRIX) values ('6',null,null,'32');
REM INSERTING into FARAH.SUPPCOM
SET DEFINE OFF;
REM INSERTING into FARAH.SUPPLEMENT
SET DEFINE OFF;
Insert into FARAH.SUPPLEMENT (IDS,NOM,TYPE,PRIX) values ('1','lll','mmm','15');
REM INSERTING into FARAH.USERS
SET DEFINE OFF;
Insert into FARAH.USERS (ID,LOGIN,PASWORD,ID_EMP,EMAIL) values ('5','farah','farah','5',null);
REM INSERTING into FARAH.VEHICULE
SET DEFINE OFF;
Insert into FARAH.VEHICULE (ID,ETAT,MODELE) values ('15','mm','ll');
Insert into FARAH.VEHICULE (ID,ETAT,MODELE) values ('12','ll','mm');
--------------------------------------------------------
--  DDL for Index CARTE_FIDELITE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARAH"."CARTE_FIDELITE_PK" ON "FARAH"."CARTE_FIDELITE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARAH"."CLIENT_PK" ON "FARAH"."CLIENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMANDEPLAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARAH"."COMMANDEPLAT_PK" ON "FARAH"."COMMANDEPLAT" ("NUMC", "ID_PLAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMANDES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARAH"."COMMANDES_PK" ON "FARAH"."COMMANDES" ("NUMC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARAH"."EMPLOYE_PK" ON "FARAH"."EMPLOYE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EQUIPEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARAH"."EQUIPEMENT_PK" ON "FARAH"."EQUIPEMENT" ("ID_EQUIPEMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURNISSEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARAH"."FOURNISSEUR_PK" ON "FARAH"."FOURNISSEUR" ("ID_FOURNISSEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LIVRAISONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARAH"."LIVRAISONS_PK" ON "FARAH"."LIVRAISONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LOGIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARAH"."LOGIN_PK" ON "FARAH"."LOGIN" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARAH"."MENU_PK" ON "FARAH"."MENU" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PANIER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARAH"."PANIER_PK" ON "FARAH"."PANIER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PLATS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARAH"."PLATS_PK" ON "FARAH"."PLATS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARAH"."PRODUIT_PK" ON "FARAH"."PRODUITS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SUPPCOM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARAH"."SUPPCOM_PK" ON "FARAH"."SUPPCOM" ("NUMC", "IDS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SUPPLEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARAH"."SUPPLEMENT_PK" ON "FARAH"."SUPPLEMENT" ("IDS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARAH"."USERS_PK" ON "FARAH"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VEHICULE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARAH"."VEHICULE_PK" ON "FARAH"."VEHICULE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger ADDSUPPTOSUM
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FARAH"."ADDSUPPTOSUM" 
AFTER INSERT OR UPDATE ON SUPPCOM
FOR EACH ROW 
DECLARE
pragma autonomous_transaction;
prixplat int;
diff int := 0;
BEGIN
select p.Prix into prixplat from SUPPLEMENT p where p.ids = :New.ids;
diff := COALESCE(:New.qty,0) - COALESCE(:Old.qty,0);
update commandes cm set cm.PrixTot = COALESCE(cm.PrixTot,0) + COALESCE(prixplat,0) * diff where cm.numc = :NEW.NUMC;
commit;
END;
/
ALTER TRIGGER "FARAH"."ADDSUPPTOSUM" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CALCULATESUM
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FARAH"."CALCULATESUM" 
AFTER INSERT OR UPDATE ON COMMANDEPLAT
FOR EACH ROW 
DECLARE
pragma autonomous_transaction;
prixplat int;
diff int := 0;
BEGIN
select p.Prix into prixplat from Plats p where p.id = :New.Id_Plat;

diff := COALESCE(:New.qty,0) - COALESCE(:Old.qty,0);

update commandes cm set cm.PrixTot = COALESCE(cm.PrixTot,0) + COALESCE(prixplat,0) * diff where cm.numc = :NEW.NUMC;
commit;
END;
/
ALTER TRIGGER "FARAH"."CALCULATESUM" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COMMANDES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FARAH"."COMMANDES_TRG" 
BEFORE INSERT ON COMMANDES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.NUMC IS NULL THEN
      SELECT COMMANDES_SEQ.NEXTVAL INTO :NEW.NUMC FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FARAH"."COMMANDES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPLOYE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FARAH"."EMPLOYE_TRG" 
BEFORE INSERT ON EMPLOYE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ADRESSE IS NULL THEN
      SELECT EMPLOYE_SEQ.NEXTVAL INTO :NEW.ADRESSE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FARAH"."EMPLOYE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPLOYE_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FARAH"."EMPLOYE_TRG1" 
BEFORE INSERT ON EMPLOYE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT EMPLOYE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FARAH"."EMPLOYE_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EQUIPEMENT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FARAH"."EQUIPEMENT_TRG" 
BEFORE INSERT ON EQUIPEMENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_EQUIPEMENT IS NULL THEN
      SELECT EQUIPEMENT_SEQ.NEXTVAL INTO :NEW.ID_EQUIPEMENT FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FARAH"."EQUIPEMENT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EQUIPEMENT_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FARAH"."EQUIPEMENT_TRG1" 
BEFORE INSERT ON EQUIPEMENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_EMPLOYEE IS NULL THEN
      SELECT EQUIPEMENT_SEQ1.NEXTVAL INTO :NEW.ID_EMPLOYEE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FARAH"."EQUIPEMENT_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MENU_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FARAH"."MENU_TRG" 
BEFORE INSERT ON MENU 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MENU_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FARAH"."MENU_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PLATS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FARAH"."PLATS_TRG" 
BEFORE INSERT ON PLATS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FARAH"."PLATS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PLATS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FARAH"."PLATS_TRG1" 
BEFORE INSERT ON PLATS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PLATS_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FARAH"."PLATS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRODUITS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FARAH"."PRODUITS_TRG" 
BEFORE INSERT ON PRODUITS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PRODUITS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FARAH"."PRODUITS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SUPPLEMENT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FARAH"."SUPPLEMENT_TRG" 
BEFORE INSERT ON SUPPLEMENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDS IS NULL THEN
      SELECT SUPPLEMENT_SEQ.NEXTVAL INTO :NEW.IDS FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FARAH"."SUPPLEMENT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FARAH"."USERS_TRG" 
BEFORE INSERT ON USERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT USERS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FARAH"."USERS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger VEHICULE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FARAH"."VEHICULE_TRG" 
BEFORE INSERT ON VEHICULE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "FARAH"."VEHICULE_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table CARTE_FIDELITE
--------------------------------------------------------

  ALTER TABLE "FARAH"."CARTE_FIDELITE" ADD CONSTRAINT "CARTE_FIDELITE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FARAH"."CARTE_FIDELITE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "FARAH"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FARAH"."CLIENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMANDEPLAT
--------------------------------------------------------

  ALTER TABLE "FARAH"."COMMANDEPLAT" ADD CONSTRAINT "COMMANDEPLAT_PK" PRIMARY KEY ("NUMC", "ID_PLAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FARAH"."COMMANDEPLAT" MODIFY ("QTY" NOT NULL ENABLE);
  ALTER TABLE "FARAH"."COMMANDEPLAT" MODIFY ("ID_PLAT" NOT NULL ENABLE);
  ALTER TABLE "FARAH"."COMMANDEPLAT" MODIFY ("NUMC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMANDES
--------------------------------------------------------

  ALTER TABLE "FARAH"."COMMANDES" ADD CONSTRAINT "COMMANDES_PK" PRIMARY KEY ("NUMC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FARAH"."COMMANDES" MODIFY ("IDEMPLOYE" NOT NULL ENABLE);
  ALTER TABLE "FARAH"."COMMANDES" MODIFY ("NUMC" NOT NULL ENABLE);
  ALTER TABLE "FARAH"."COMMANDES" MODIFY ("DATEC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "FARAH"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FARAH"."EMPLOYE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPEMENT
--------------------------------------------------------

  ALTER TABLE "FARAH"."EQUIPEMENT" ADD CONSTRAINT "EQUIPEMENT_PK" PRIMARY KEY ("ID_EQUIPEMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FARAH"."EQUIPEMENT" MODIFY ("ID_EQUIPEMENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURNISSEUR
--------------------------------------------------------

  ALTER TABLE "FARAH"."FOURNISSEUR" ADD CONSTRAINT "FOURNISSEUR_PK" PRIMARY KEY ("ID_FOURNISSEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FARAH"."FOURNISSEUR" MODIFY ("ID_FOURNISSEUR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LIVRAISONS
--------------------------------------------------------

  ALTER TABLE "FARAH"."LIVRAISONS" ADD CONSTRAINT "LIVRAISONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FARAH"."LIVRAISONS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOGIN
--------------------------------------------------------

  ALTER TABLE "FARAH"."LOGIN" ADD CONSTRAINT "LOGIN_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FARAH"."LOGIN" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "FARAH"."MENU" ADD CONSTRAINT "MENU_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FARAH"."MENU" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PANIER
--------------------------------------------------------

  ALTER TABLE "FARAH"."PANIER" ADD CONSTRAINT "PANIER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FARAH"."PANIER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLATS
--------------------------------------------------------

  ALTER TABLE "FARAH"."PLATS" ADD CONSTRAINT "PLATS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FARAH"."PLATS" MODIFY ("ID_MENU" NOT NULL ENABLE);
  ALTER TABLE "FARAH"."PLATS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUITS
--------------------------------------------------------

  ALTER TABLE "FARAH"."PRODUITS" ADD CONSTRAINT "PRODUIT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FARAH"."PRODUITS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUPPCOM
--------------------------------------------------------

  ALTER TABLE "FARAH"."SUPPCOM" ADD CONSTRAINT "SUPPCOM_PK" PRIMARY KEY ("NUMC", "IDS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FARAH"."SUPPCOM" MODIFY ("IDS" NOT NULL ENABLE);
  ALTER TABLE "FARAH"."SUPPCOM" MODIFY ("NUMC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUPPLEMENT
--------------------------------------------------------

  ALTER TABLE "FARAH"."SUPPLEMENT" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "FARAH"."SUPPLEMENT" ADD CONSTRAINT "SUPPLEMENT_PK" PRIMARY KEY ("IDS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FARAH"."SUPPLEMENT" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "FARAH"."SUPPLEMENT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "FARAH"."SUPPLEMENT" MODIFY ("IDS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "FARAH"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FARAH"."USERS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VEHICULE
--------------------------------------------------------

  ALTER TABLE "FARAH"."VEHICULE" ADD CONSTRAINT "VEHICULE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FARAH"."VEHICULE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COMMANDEPLAT
--------------------------------------------------------

  ALTER TABLE "FARAH"."COMMANDEPLAT" ADD CONSTRAINT "COMMANDEPLAT_FK1" FOREIGN KEY ("NUMC")
	  REFERENCES "FARAH"."COMMANDES" ("NUMC") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FARAH"."COMMANDEPLAT" ADD CONSTRAINT "COMMANDEPLAT_FK2" FOREIGN KEY ("ID_PLAT")
	  REFERENCES "FARAH"."PLATS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EQUIPEMENT
--------------------------------------------------------

  ALTER TABLE "FARAH"."EQUIPEMENT" ADD CONSTRAINT "EQUIPEMENT_FK1" FOREIGN KEY ("ID_EMPLOYEE")
	  REFERENCES "FARAH"."EMPLOYE" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FOURNISSEUR
--------------------------------------------------------

  ALTER TABLE "FARAH"."FOURNISSEUR" ADD CONSTRAINT "FOURNISSEUR_FK1" FOREIGN KEY ("ID_PRODUIT")
	  REFERENCES "FARAH"."PRODUITS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LIVRAISONS
--------------------------------------------------------

  ALTER TABLE "FARAH"."LIVRAISONS" ADD CONSTRAINT "LIVRAISONS_FK1" FOREIGN KEY ("ID_V")
	  REFERENCES "FARAH"."VEHICULE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLATS
--------------------------------------------------------

  ALTER TABLE "FARAH"."PLATS" ADD CONSTRAINT "PLATS_FK1" FOREIGN KEY ("ID_MENU")
	  REFERENCES "FARAH"."MENU" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUPPCOM
--------------------------------------------------------

  ALTER TABLE "FARAH"."SUPPCOM" ADD CONSTRAINT "SUPPCOM_FK1" FOREIGN KEY ("IDS")
	  REFERENCES "FARAH"."SUPPLEMENT" ("IDS") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FARAH"."SUPPCOM" ADD CONSTRAINT "SUPPCOM_FK2" FOREIGN KEY ("NUMC")
	  REFERENCES "FARAH"."COMMANDES" ("NUMC") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "FARAH"."USERS" ADD CONSTRAINT "USERS_FK1" FOREIGN KEY ("ID_EMP")
	  REFERENCES "FARAH"."USERS" ("ID") ENABLE;
